#!/usr/bin/env python3
"""
ru_aibotworks_charter.py — generate the charter from the registry.

The charter used to be hand-authored, and the figures in it drifted from the
company the moment the company changed. Invariant 11 says any figure appearing in
two documents derives from one computed source; the honest way to hold that is to
stop typing figures into documents at all.

Emits into DOCS/charter/:

    01-start-here.md     the constitution and the standing rules
    02-organisation.md   officers, vetoes, departments, dispatch
    03-roster.md         every agent, by division and team

    python ru_aibotworks_charter.py
"""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ru_aibotworks_registry import Company, as_of  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "DOCS" / "charter"
AS_OF = as_of()  # registry edition date, never the wall clock

BANNER = (
    "<!-- GENERATED by PLATFORM/ru_aibotworks_charter.py from the registry.\n"
    "     Do not hand-edit. Change REGISTRY and regenerate. -->\n"
)


def start_here(c: Company) -> str:
    f = c.figures
    ident = c.identity
    return f"""# RU-AIBOTWORKS — start here

{BANNER}
**CEO:** {ident['ceo']['full']} · **Officers:** {f['officers']} ·
**Workforce:** {f['workforce_total']} · **{f['agents_total']} agents total**

## What this company is

A software company with one human and **{f['agents_total']} agents**.

{f['officers']} of them are officers who decide, review and stop releases. The other
{f['workforce_total']} do the work, across {f['departments']} departments and
{f['teams']} teams. Every one of them was designed here, carries a registration
record, a declared blast radius, a tool contract and at least one skill.

Each agent has two identities: a **handle** that the system dispatches and that
appears in every receipt, and a **name** that people use. `python-pro` is the
handle. Yuki is the person.

## What it sells

Ten website templates and mobile applications, built to order, through a gate
nothing bypasses. The product is not the code — everyone has AI writing code now.
The product is **provable build quality**:

- Deterministic gate jobs, all green or nothing ships
- A read-only reviewer reporting outside the team that wrote the code
- Human approval before any merge
- **{f['vetoes']} standing vetoes**, only the CEO overrides
- An Ed25519-signed, hash-chained, offline-verifiable receipt for every action

## The ten standing rules

**1. Every agent is owned and governed.** All {f['agents_total']} carry a reporting
line, a decision level, a tier ceiling and a blast radius that is a number.

**2. No orchestrator answers `/build`.** Capability does not confer authority. An
orchestrator is invoked *by* an officer, *inside* a phase.

**3. The registry is the source of truth.** Agent charters, registration records,
tool contracts, the database seed and the portal are all generated from it. Editing
a generated file is a defect the gate catches.

**4. Every figure is computed.** No document asserts a headcount. This one included.

**5. Certify before use.** Every dependency is pinned by commit and certified before
first use and on every bump.

**6. Policy is written from receipts, never imagination.** Audit mode runs for one
full build first. Policy written ahead of evidence becomes an obstacle, and
obstacles get loosened under deadline.

**7. A flaky check never blocks promotion.** A flaky blocker teaches people to
bypass the gate.

**8. Tier C is uninstalled between projects.** The discipline everyone skips.

**9. Every project has a `DESIGN.md`.** The only defence against ten siblings.

**10. The CEO cannot be the one who ships.** Officers under delivery pressure must
not hold the stop button.

## The {f['reserved_decisions']} decisions that are yours alone

| Decision | Why it cannot be delegated |
|---|---|
| **What to build** | Commercial priority |
| **Whether the design is right** | The anti-sameness judgement |
| **Whether to override a veto** | {f['vetoes']} officers can stop a release; only you unstop it |
| **Off-stack technology** | Changes cost structure, not just stack |

## The shape of the company

| | |
|---|---|
| Divisions | {f['divisions']} — Delivery, Corporate, Independent |
| Departments | {f['departments']} |
| Teams | {f['teams']} |
| Officers | {f['officers']} ({f['officers_original']} original + {f['officers_added']} added) |
| Delivery engineers | {f['engineers_delivery_baseline']} |
| Mobile engineers | {f['engineers_mobile_expansion']} |
| Corporate staff | {f['staff_corporate']} |
| Skills | {f['skills_total']} |
| Registered tools | {f['tools_registered']} ({f['tools_granted']} grantable, {f['tools_registered_denied']} denied to all) |
| Highest tier any agent may request | {f['max_tier_granted']} |
| Deepest reporting chain | {f['deepest_chain']} hops |

## The document set

| Document | Answers |
|---|---|
| `build-plan.md` | Every stage, in order, and where we are |
| `adr/ADR-001` | Why agents are built rather than forked |
| `adr/ADR-002` | The organisation, and why it has {f['officers']} officers |
| `adr/ADR-003` | The mobile lane and its three stacks |
| `adr/ADR-004` | Compliance: what attaches, when, and to which template |
| `adr/ADR-005` | What an agent, a sub-agent and a skill actually are |
| `charter/02-organisation.md` | **Generated** — officers, vetoes, departments |
| `charter/03-roster.md` | **Generated** — every agent in the company |

Generated {AS_OF.isoformat()}.
"""


def organisation(c: Company) -> str:
    f = c.figures
    officer_rows = "\n".join(
        f"| `{o.name}` | {o.person} | {o.level} | `{o.reports_to}` | {o.function} | "
        f"{o.decides} | {o.model} | {o.power or '—'} | {'ADR-002' if o.added != 'original' else 'original'} |"
        for o in c.officers
    )
    veto_rows = "\n".join(
        f"| `{o.name}` ({o.person}) | {o.decides} | CEO only |"
        for o in c.officers if o.power == "VETO"
    )
    dept_rows = "\n".join(
        f"| {d['name']} | {d['division']} | `{d['officer']}` | {len(d['teams'])} | "
        f"{len(c.agents_in(d['id']))} | {d['mission']} |"
        for d in c.departments
    )
    return f"""# Organisation — RU-AIBOTWORKS

{BANNER}
**{f['officers']} officers · {f['workforce_total']} workforce · {f['agents_total']} agents ·
{f['vetoes']} standing vetoes · {f['divisions']} divisions · {f['departments']} departments ·
{f['teams']} teams · deepest chain {f['deepest_chain']}**

## The chart

```mermaid
flowchart TD
    CEO["CEO · {c.identity['ceo']['name']} · L5"]
    CEO --> CTO["cto · L4 · Delivery"]
    CEO --> COO["coo · L4 · Corporate"]
    CEO --> DPO["data-protection-officer · L3 · Independent"]
    CTO --> PO["product-owner · L3"]
    CTO --> DO["design-owner · L3"]
    CTO --> WA["web-architect · L3"]
    CTO --> DA["data-architect · L3"]
    CTO --> PA["platform-architect · L3"]
    CTO --> TA["testing-architect · L3"]
    CTO --> QC["quality-compliance · L3 · VETO"]
    TA --> MA["merge-authority · L2 · READ-ONLY"]
    PA --> SEC["security-engineer · L2 · VETO"]
    PA --> SRE["sre · L2 · VETO"]
    PA --> RM["release-manager · L2"]
    PA --> DS["dependency-steward · L2"]
    COO --> HR["hr-director · L3"]
    COO --> PAY["payroll-controller · L3"]
    COO --> FIN["finance-controller · L3"]
    COO --> SVC["service-management-lead · L3"]
    MA -.reviews.-> WA
    MA -.reviews.-> DA
    DPO -.advises.-> QC
```

`merge-authority` reports to `testing-architect`, **not** to the architects it
reviews. That edge is why verification cannot be overruled by the team it verifies.

`data-protection-officer` reports to the CEO directly, because GDPR Art. 38(3)
requires the DPO to reach the highest management level and to take no instruction on
how to perform the role.

## The {f['officers']} officers

| Officer | Name | Level | Reports to | Function | Decides | Model | Power | Added |
|---|---|---|---|---|---|---|---|---|
{officer_rows}

{f['chiefs_l4']} at L4, {f['officers_l3']} at L3, {f['officers_l2']} at L2, one human L5.

## Vetoes

Exactly {f['vetoes']}, and the count is enforced on every build.

| Holder | Blocks on | Override |
|---|---|---|
{veto_rows}

Neither `cto` nor `coo` can override any of them. An autonomous chief *is* delivery
pressure and must not reach its own stop buttons.

The Data Protection Officer holds **no veto**. It raises findings;
`quality-compliance` blocks on them. Under GDPR the DPO advises, monitors and
reports — it does not hold an operational stop button.

## The {f['departments']} departments

| Department | Division | Officer | Teams | Staff | Mission |
|---|---|---|---|---|---|
{dept_rows}

## Team leads

{f['teams']} teams, {f['teams']} leads. {f['team_leads_promoted_l2']} hold **L2** by
deliberate, logged promotion — an officer's request, a written reason and a date.
The other {f['team_leads_coordinating_l1']} stay at **L1** because their department's
officer is itself L2: there is no room above them, and an L2 reporting to an L2
inverts authority. Those departments are flat, and the lead coordinates without a
reporting line beneath it.

Generated {AS_OF.isoformat()}.
"""


def roster(c: Company) -> str:
    f = c.figures
    sections = []
    for dept in c.departments:
        officer = c.officer_by_name[dept["officer"]]
        members = c.agents_in(dept["id"])
        sections.append(
            f"\n## {dept['name']} · `{officer.name}` ({officer.person}) · "
            f"{dept['division']} · {len(members)} staff\n\n> {dept['mission']}\n"
        )
        for team in dept["teams"]:
            tm = c.agents_in(dept["id"], team["id"])
            lead = c.agent_by_name[team["lead"]]
            sections.append(
                f"\n### {team['name']} — lead `{team['lead']}` ({lead.person}) · "
                f"{len(tm)} members\n\n{team['mission']}\n\n"
                "| Name | Handle | Level | Model | Tier | Skills | Reports to | Role |\n"
                "|---|---|---|---|---|---|---|---|\n"
            )
            for a in tm:
                flags = " **LEAD**" if a.lead else ""
                flags += " *(read-only)*" if a.read_only else ""
                sections.append(
                    f"| {a.person}{flags} | `{a.name}` | {a.level} | {a.model} | "
                    f"{a.tier} | {len(a.skills)} | `{c.reports_to_of(a)}` | {a.role} |\n"
                )
    model_rows = "\n".join(
        f"| {m} | {n} |" for m, n in f["model_mix"].items()
    )
    return f"""# Employee roster — RU-AIBOTWORKS

{BANNER}
**{f['workforce_total']} agents below the officer layer** · {f['officers']} officers ·
1 CEO · **{f['agents_total']} agents total**

Every agent below carries a name, a handle, a reporting line, a decision level, a
tier ceiling, a blast radius and at least one skill. An agent missing any of those
fails the build.

## Headcount

| Cohort | Count |
|---|---|
| Delivery engineers (charter baseline) | {f['engineers_delivery_baseline']} |
| Mobile engineers (Lane C) | {f['engineers_mobile_expansion']} |
| Corporate staff | {f['staff_corporate']} |
| **Workforce total** | **{f['workforce_total']}** |
| Officers | {f['officers']} |
| **Company total** | **{f['agents_total']}** |

## Model mix

| Model | Agents |
|---|---|
{model_rows}

## Tier ceilings

| Tier | Agents | Meaning |
|---|---|---|
| 0 | {f['tier_mix'].get(0, 0)} | Read-only. No state change of any kind. |
| 1 | {f['tier_mix'].get(1, 0)} | Reversible and cheap. Undo in seconds. |
| 2 | {f['tier_mix'].get(2, 0)} | Reversible but expensive. Undo needs a restore, and the rollback is recorded. |

No agent may request Tier 3 or Tier 4. There is no autonomy level at which Tier 4
becomes automatic.
{"".join(sections)}
Generated {AS_OF.isoformat()}.
"""


def main() -> int:
    c = Company.load()
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "01-start-here.md": start_here(c),
        "02-organisation.md": organisation(c),
        "03-roster.md": roster(c),
    }
    for name, text in files.items():
        (OUT / name).write_text(text, encoding="utf-8")
    total = sum(len(t) for t in files.values())
    print(f"charter generated - {len(files)} documents, {total // 1024} KB")
    for name in files:
        print(f"  charter/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
