#!/usr/bin/env python3
"""
ru_aibotworks_seed_sql.py — emit the SQL Server seed from the registry.

Writes DATABASE/RU-AIBOTWORKS-seed.sql, which loads the whole company
into RU_AIBOTWORKS. Generated rather than hand-written for the same reason every other
artifact here is: the registry is the only place a company fact may originate.

Every parent table is loaded with MERGE guarded by an EXCEPT comparison, so a re-run
that changes nothing writes no history. gov.Officer and gov.Agent are system-versioned;
touching an unchanged row would fabricate an org change that never happened.

    python ru_aibotworks_seed_sql.py
    sqlcmd -S localhost -E -C -b -i DATABASE/RU-AIBOTWORKS-seed.sql
"""
from __future__ import annotations

import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ru_aibotworks_generate import (  # noqa: E402
    BUDGETS,
    blast_radius_for,
    classification_for,
    grants_for,
)
from ru_aibotworks_registry import Company, as_of  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "DATABASE" / "RU-AIBOTWORKS-seed.sql"
AS_OF = as_of()  # registry edition date, never the wall clock
REVIEW_DUE = AS_OF + timedelta(days=182)


def q(value) -> str:
    """Quote a value for T-SQL. None becomes NULL; quotes are doubled."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "N'" + str(value).replace("'", "''") + "'"


def merge(table: str, columns: list[str], keys: list[str], rows: list[tuple]) -> str:
    """MERGE that only updates genuinely changed rows, and removes what is gone."""
    if not rows:
        return f"DELETE FROM {table};\nGO\n"
    collist = ", ".join(f"[{c}]" for c in columns)
    values = ",\n        ".join("(" + ", ".join(q(v) for v in row) + ")" for row in rows)
    on = " AND ".join(f"tgt.[{k}] = src.[{k}]" for k in keys)
    non_key = [c for c in columns if c not in keys]
    setters = ", ".join(f"tgt.[{c}] = src.[{c}]" for c in non_key)
    src_cols = ", ".join(f"src.[{c}]" for c in non_key)
    tgt_cols = ", ".join(f"tgt.[{c}]" for c in non_key)

    update_clause = ""
    if non_key:
        update_clause = f"""
WHEN MATCHED AND EXISTS (
        SELECT {src_cols} EXCEPT SELECT {tgt_cols}
     ) THEN UPDATE SET {setters}"""

    return f"""
;WITH src ({collist}) AS (
    SELECT * FROM (VALUES
        {values}
    ) v ({collist})
)
MERGE {table} AS tgt
USING src ON {on}{update_clause}
WHEN NOT MATCHED BY TARGET THEN
    INSERT ({collist}) VALUES ({", ".join(f"src.[{c}]" for c in columns)})
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO
"""


def build(company: Company) -> str:
    ident = company.identity
    out: list[str] = []
    add = out.append

    add(f"""/* ============================================================================
   RU-AIBOTWORKS — database seed
   GENERATED by PLATFORM/ru_aibotworks_seed_sql.py on {AS_OF.isoformat()}.
   Do not hand-edit. Change REGISTRY and regenerate.

   {ident['company']['name']} · CEO {ident['ceo']['full']}
   {company.figures['agents_total']} agents · {company.figures['officers']} officers ·
   {company.figures['departments']} departments · {company.figures['teams']} teams
   ============================================================================ */

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
USE RU_AIBOTWORKS;
GO
BEGIN TRANSACTION;
GO
""")

    # ── child tables cleared first, so parents can be reshaped ──────────────
    add("""
DELETE FROM gov.AgentTool;
DELETE FROM gov.AgentDomain;
DELETE FROM gov.Skill;
DELETE FROM gov.Promotion;
DELETE FROM gov.ToolBlockedIf;
DELETE FROM gov.TemplateRegime;
GO
""")

    # ── authority levels ───────────────────────────────────────────────────
    add(merge(
        "gov.AuthorityLevel",
        ["Level", "Rank", "HeldBy", "MayDecide", "MayNot"],
        ["Level"],
        [
            ("L1", 1, "every engineer", "Implementation approach inside an assigned task",
             "Decide scope, merge, or ship"),
            ("L2", 2, "5 named officers and promoted team leads",
             "One named call each, or the sequencing of one team", "Anything outside that call"),
            ("L3", 3, "12 officers", "Anything binding their function", "Cross into another function"),
            ("L4", 4, "cto and coo", "Triage, dispatch, corporate direction", "Override a veto"),
            ("L5", 5, "CEO - human, 1", "Commercial direction and veto override", "Ship code"),
        ],
    ))

    # ── divisions ──────────────────────────────────────────────────────────
    divisions = sorted({d["division"] for d in company.departments})
    division_desc = {
        "Delivery": "Builds and ships the ten templates. Reports through the CTO.",
        "Corporate": "HR, Payroll, Finance and Service Management. Reports through the COO.",
        "Independent": "Data protection. Reports to the CEO directly for independence.",
    }
    add(merge("gov.Division", ["Name", "Description"], ["Name"],
              [(d, division_desc.get(d)) for d in divisions]))

    # ── officers ───────────────────────────────────────────────────────────
    officer_rows = [
        (o.name, o.person, o.level, o.reports_to, o.division, o.function, o.model,
         o.power, o.decides, o.max_tier, o.read_only, o.added)
        for o in company.officers
    ]
    add(f"""
;WITH src (Name, Person, Level, ReportsTo, DivisionName, [Function], Model, Power,
           Decides, MaxTier, IsReadOnly, AddedBy) AS (
    SELECT * FROM (VALUES
        {",\n        ".join("(" + ", ".join(q(v) for v in row) + ")" for row in officer_rows)}
    ) v (Name, Person, Level, ReportsTo, DivisionName, [Function], Model, Power,
         Decides, MaxTier, IsReadOnly, AddedBy)
), resolved AS (
    SELECT src.*, d.DivisionId FROM src JOIN gov.Division d ON d.Name = src.DivisionName
)
MERGE gov.Officer AS tgt
USING resolved AS src ON tgt.Name = src.Name
WHEN MATCHED AND EXISTS (
        SELECT src.Person, src.Level, src.ReportsTo, src.DivisionId, src.[Function],
               src.Model, src.Power, src.Decides, src.MaxTier, src.IsReadOnly, src.AddedBy
        EXCEPT
        SELECT tgt.Person, tgt.Level, tgt.ReportsTo, tgt.DivisionId, tgt.[Function],
               tgt.Model, tgt.Power, tgt.Decides, tgt.MaxTier, tgt.IsReadOnly, tgt.AddedBy
     ) THEN UPDATE SET
        tgt.Person = src.Person,
        tgt.Level = src.Level, tgt.ReportsTo = src.ReportsTo, tgt.DivisionId = src.DivisionId,
        tgt.[Function] = src.[Function], tgt.Model = src.Model, tgt.Power = src.Power,
        tgt.Decides = src.Decides, tgt.MaxTier = src.MaxTier,
        tgt.IsReadOnly = src.IsReadOnly, tgt.AddedBy = src.AddedBy
WHEN NOT MATCHED BY TARGET THEN
    INSERT (Name, Person, Level, ReportsTo, DivisionId, [Function], Model, Power,
            Decides, MaxTier, IsReadOnly, AddedBy)
    VALUES (src.Name, src.Person, src.Level, src.ReportsTo, src.DivisionId, src.[Function],
            src.Model, src.Power, src.Decides, src.MaxTier, src.IsReadOnly, src.AddedBy)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO
""")

    # ── departments ────────────────────────────────────────────────────────
    dept_rows = [
        (d["id"], d["name"], d["division"], d["officer"], d["mission"])
        for d in company.departments
    ]
    add(f"""
;WITH src (Code, Name, DivisionName, OfficerName, Mission) AS (
    SELECT * FROM (VALUES
        {",\n        ".join("(" + ", ".join(q(v) for v in row) + ")" for row in dept_rows)}
    ) v (Code, Name, DivisionName, OfficerName, Mission)
), resolved AS (
    SELECT src.Code, src.Name, src.Mission, d.DivisionId, o.OfficerId
    FROM src JOIN gov.Division d ON d.Name = src.DivisionName
             JOIN gov.Officer  o ON o.Name = src.OfficerName
)
MERGE gov.Department AS tgt
USING resolved AS src ON tgt.Code = src.Code
WHEN MATCHED AND EXISTS (
        SELECT src.Name, src.DivisionId, src.OfficerId, src.Mission
        EXCEPT SELECT tgt.Name, tgt.DivisionId, tgt.OfficerId, tgt.Mission
     ) THEN UPDATE SET tgt.Name = src.Name, tgt.DivisionId = src.DivisionId,
                       tgt.OfficerId = src.OfficerId, tgt.Mission = src.Mission
WHEN NOT MATCHED BY TARGET THEN
    INSERT (Code, Name, DivisionId, OfficerId, Mission)
    VALUES (src.Code, src.Name, src.DivisionId, src.OfficerId, src.Mission)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO
""")

    # ── teams ──────────────────────────────────────────────────────────────
    team_rows = [
        (t["id"], t["name"], t["department"], t["lead"], t["mission"]) for t in company.teams
    ]
    add(f"""
;WITH src (Code, Name, DeptCode, LeadAgentName, Mission) AS (
    SELECT * FROM (VALUES
        {",\n        ".join("(" + ", ".join(q(v) for v in row) + ")" for row in team_rows)}
    ) v (Code, Name, DeptCode, LeadAgentName, Mission)
), resolved AS (
    SELECT src.Code, src.Name, src.LeadAgentName, src.Mission, d.DepartmentId
    FROM src JOIN gov.Department d ON d.Code = src.DeptCode
)
MERGE gov.Team AS tgt
USING resolved AS src ON tgt.Code = src.Code AND tgt.DepartmentId = src.DepartmentId
WHEN MATCHED AND EXISTS (
        SELECT src.Name, src.LeadAgentName, src.Mission
        EXCEPT SELECT tgt.Name, tgt.LeadAgentName, tgt.Mission
     ) THEN UPDATE SET tgt.Name = src.Name, tgt.LeadAgentName = src.LeadAgentName,
                       tgt.Mission = src.Mission
WHEN NOT MATCHED BY TARGET THEN
    INSERT (Code, Name, DepartmentId, LeadAgentName, Mission)
    VALUES (src.Code, src.Name, src.DepartmentId, src.LeadAgentName, src.Mission)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO
""")

    # ── agents ─────────────────────────────────────────────────────────────
    agent_rows = []
    for a in company.agents:
        budget = BUDGETS[a.tier]
        agent_rows.append((
            a.name, a.person, a.team, a.department, company.reports_to_of(a), a.level, a.role,
            a.model, a.plugin, a.tier, a.lead, a.read_only, a.cohort,
            classification_for(a),
            "L0-propose-only" if a.tier == 0 else "L1-supervised",
            blast_radius_for(a, company),
            budget["steps"], budget["tokens"], budget["mutations"],
            AS_OF.isoformat(), REVIEW_DUE.isoformat(),
        ))
    cols = ("Name, Person, TeamCode, DeptCode, ReportsTo, DecisionLevel, [Role], Model, Capability, "
            "MaxTier, IsTeamLead, IsReadOnly, Cohort, Classification, AutonomyLevel, "
            "BlastRadius, BudgetSteps, BudgetTokens, BudgetMutations, RegisteredOn, ReviewDue")
    add(f"""
;WITH src ({cols}) AS (
    SELECT * FROM (VALUES
        {",\n        ".join("(" + ", ".join(q(v) for v in row) + ")" for row in agent_rows)}
    ) v ({cols})
), resolved AS (
    SELECT src.*, t.TeamId, d.DepartmentId
    FROM src JOIN gov.Department d ON d.Code = src.DeptCode
             JOIN gov.Team       t ON t.Code = src.TeamCode AND t.DepartmentId = d.DepartmentId
)
MERGE gov.Agent AS tgt
USING resolved AS src ON tgt.Name = src.Name
WHEN MATCHED AND EXISTS (
        SELECT src.Person, src.TeamId, src.DepartmentId, src.ReportsTo, src.DecisionLevel, src.[Role],
               src.Model, src.Capability, src.MaxTier, src.IsTeamLead, src.IsReadOnly,
               src.Cohort, src.Classification, src.AutonomyLevel, src.BlastRadius,
               src.BudgetSteps, src.BudgetTokens, src.BudgetMutations
        EXCEPT
        SELECT tgt.Person, tgt.TeamId, tgt.DepartmentId, tgt.ReportsTo, tgt.DecisionLevel, tgt.[Role],
               tgt.Model, tgt.Capability, tgt.MaxTier, tgt.IsTeamLead, tgt.IsReadOnly,
               tgt.Cohort, tgt.Classification, tgt.AutonomyLevel, tgt.BlastRadius,
               tgt.BudgetSteps, tgt.BudgetTokens, tgt.BudgetMutations
     ) THEN UPDATE SET
        tgt.Person = src.Person, tgt.TeamId = src.TeamId, tgt.DepartmentId = src.DepartmentId,
        tgt.ReportsTo = src.ReportsTo, tgt.DecisionLevel = src.DecisionLevel,
        tgt.[Role] = src.[Role], tgt.Model = src.Model, tgt.Capability = src.Capability,
        tgt.MaxTier = src.MaxTier, tgt.IsTeamLead = src.IsTeamLead,
        tgt.IsReadOnly = src.IsReadOnly, tgt.Cohort = src.Cohort,
        tgt.Classification = src.Classification, tgt.AutonomyLevel = src.AutonomyLevel,
        tgt.BlastRadius = src.BlastRadius, tgt.BudgetSteps = src.BudgetSteps,
        tgt.BudgetTokens = src.BudgetTokens, tgt.BudgetMutations = src.BudgetMutations,
        tgt.ReviewDue = src.ReviewDue
WHEN NOT MATCHED BY TARGET THEN
    INSERT (Name, Person, TeamId, DepartmentId, ReportsTo, DecisionLevel, [Role], Model, Capability,
            MaxTier, IsTeamLead, IsReadOnly, Cohort, Classification, AutonomyLevel,
            BlastRadius, BudgetSteps, BudgetTokens, BudgetMutations, RegisteredOn, ReviewDue)
    VALUES (src.Name, src.Person, src.TeamId, src.DepartmentId, src.ReportsTo, src.DecisionLevel,
            src.[Role], src.Model, src.Capability, src.MaxTier, src.IsTeamLead,
            src.IsReadOnly, src.Cohort, src.Classification, src.AutonomyLevel,
            src.BlastRadius, src.BudgetSteps, src.BudgetTokens, src.BudgetMutations,
            src.RegisteredOn, src.ReviewDue)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO
""")

    # ── tools ──────────────────────────────────────────────────────────────
    tool_rows = []
    blocked_rows = []
    for t in company.tools["tools"]:
        grantable = t.get("granted_to") != []
        gates = t.get("gates", {})
        tool_rows.append((
            t["name"], t["version"], t["owner"], t["description"], t["irreversibility"],
            t["idempotent"],
            None if t["rollback"] in (None, "none", "null") else t["rollback"],
            t["scope"]["resource_pattern"], gates.get("approval", "none"),
            t["limits"]["per_task"], t["limits"]["mutation_budget"],
            t["evidence"]["retention_days"], grantable,
        ))
        for condition in gates.get("blocked_if", []):
            blocked_rows.append((t["name"], condition))

    add(merge(
        "gov.Tool",
        ["Name", "Version", "Owner", "Description", "Irreversibility", "Idempotent",
         "Rollback", "ResourcePattern", "Approval", "PerTaskLimit", "MutationBudget",
         "RetentionDays", "IsGrantable"],
        ["Name"],
        tool_rows,
    ))

    add(f"""
INSERT INTO gov.ToolBlockedIf (ToolId, Condition)
SELECT t.ToolId, v.Condition
FROM (VALUES
    {",\n    ".join("(" + ", ".join(q(x) for x in row) + ")" for row in blocked_rows)}
) v (ToolName, Condition)
JOIN gov.Tool t ON t.Name = v.ToolName;
GO
""")

    # ── agent domains, skills, tool grants ─────────────────────────────────
    domain_rows = [(a.name, d) for a in company.agents for d in a.domains]
    add(f"""
INSERT INTO gov.AgentDomain (AgentId, Domain)
SELECT ag.AgentId, v.Domain
FROM (VALUES
    {",\n    ".join("(" + ", ".join(q(x) for x in row) + ")" for row in domain_rows)}
) v (AgentName, Domain)
JOIN gov.Agent ag ON ag.Name = v.AgentName;
GO
""")

    skill_rows = [(a.name, s["id"], s["about"]) for a in company.agents for s in a.skills]
    add(f"""
INSERT INTO gov.Skill (OwnerAgentId, Code, About)
SELECT ag.AgentId, v.Code, v.About
FROM (VALUES
    {",\n    ".join("(" + ", ".join(q(x) for x in row) + ")" for row in skill_rows)}
) v (AgentName, Code, About)
JOIN gov.Agent ag ON ag.Name = v.AgentName;
GO
""")

    grant_rows = [(a.name, tool) for a in company.agents for tool in grants_for(a)]
    # emitted in batches: one VALUES list of ~2000 rows exceeds the 1000-row limit
    for i in range(0, len(grant_rows), 900):
        chunk = grant_rows[i:i + 900]
        add(f"""
INSERT INTO gov.AgentTool (AgentId, ToolId)
SELECT ag.AgentId, t.ToolId
FROM (VALUES
    {",\n    ".join("(" + ", ".join(q(x) for x in row) + ")" for row in chunk)}
) v (AgentName, ToolName)
JOIN gov.Agent ag ON ag.Name = v.AgentName
JOIN gov.Tool  t  ON t.Name  = v.ToolName;
GO
""")

    # ── promotions ─────────────────────────────────────────────────────────
    promo_rows = []
    for team in company.teams:
        lead = company.agent_by_name[team["lead"]]
        officer = company.officer_of(lead)
        reason = (
            f"Appointed lead of {team['name']}. Promoted to L2 so the team has a "
            f"coordination layer between its members and {officer.name}."
            if lead.level == "L2" else
            f"Appointed lead of {team['name']}. Remains L1 because {officer.name} is "
            f"itself L2; promoting would invert authority. Coordinates without a "
            f"reporting line beneath it."
        )
        promo_rows.append((
            lead.name, lead.level, f"{team['department']}/{team['id']}",
            officer.name, reason, AS_OF.isoformat(),
        ))
    add(f"""
INSERT INTO gov.Promotion (AgentId, ToLevel, TeamCode, RequestedBy, Reason, PromotedOn)
SELECT ag.AgentId, v.ToLevel, v.TeamCode, v.RequestedBy, v.Reason, v.PromotedOn
FROM (VALUES
    {",\n    ".join("(" + ", ".join(q(x) for x in row) + ")" for row in promo_rows)}
) v (AgentName, ToLevel, TeamCode, RequestedBy, Reason, PromotedOn)
JOIN gov.Agent ag ON ag.Name = v.AgentName;
GO
""")

    # ── reserved decisions, lanes, templates, regimes ──────────────────────
    rationale = {
        "what to build": "Commercial priority.",
        "whether the design is right": "The anti-sameness judgement.",
        "whether to override a veto": "Three officers can stop a release; only the CEO unstops it.",
        "off-stack technology": "Changes cost structure, not just stack.",
    }
    add(merge("gov.ReservedDecision", ["Decision", "Rationale"], ["Decision"],
              [(d, rationale.get(d)) for d in ident["reserved_decisions"]]))

    add(merge("gov.Lane", ["Code", "Label", "Stack"], ["Code"],
              [(k, v["label"], v["stack"]) for k, v in ident["lanes"].items()]))

    add(merge("gov.Template", ["TemplateId", "Code", "LaneCode", "IsKeystone"], ["TemplateId"],
              [(t["n"], t["id"], t["lane"], t["keystone"]) for t in ident["templates"]]))

    regime_owner = {
        "STD-AGENT-001": "platform-architect", "ISO/IEC 42001": "quality-compliance",
        "EU AI Act Art. 12/14/19": "quality-compliance", "GDPR": "data-protection-officer",
        "OWASP Top 10 for Agentic Applications 2026": "security-engineer",
        "WCAG 2.2 AA": "design-owner", "HIPAA": "data-protection-officer",
        "PCI-DSS": "security-engineer", "SOC2": "quality-compliance",
    }
    regimes = [(r, "company", regime_owner[r]) for r in ident["compliance"]["always"]]
    regimes += [(r, "project", regime_owner[r]) for r in ident["compliance"]["conditional"]]
    add(merge("gov.ComplianceRegime", ["Code", "Scope", "OwnerOfficer"], ["Code"], regimes))

    template_no = {t["id"]: t["n"] for t in ident["templates"]}
    tr_rows = []
    for regime, templates in ident["compliance"]["conditional"].items():
        for tpl in templates:
            tr_rows.append((template_no[tpl], regime))
    add(f"""
INSERT INTO gov.TemplateRegime (TemplateId, RegimeCode)
SELECT v.TemplateId, v.RegimeCode
FROM (VALUES
    {",\n    ".join("(" + ", ".join(q(x) for x in row) + ")" for row in tr_rows)}
) v (TemplateId, RegimeCode);
GO
""")

    # ── rate cards ─────────────────────────────────────────────────────────
    rate_rows = [
        (m, AS_OF.isoformat(), v["input"], v["output"], v["note"])
        for m, v in ident["models"].items()
    ]
    add(merge("fin.RateCard",
              ["Model", "EffectiveFrom", "InputPerMTok", "OutputPerMTok", "Note"],
              ["Model", "EffectiveFrom"], rate_rows))

    add("""
COMMIT TRANSACTION;
GO

/* ── verification: the figures the CEO portal quotes ─────────────────────── */
SELECT 'officers'    AS Figure, COUNT(*) AS Value FROM gov.Officer
UNION ALL SELECT 'agents',      COUNT(*) FROM gov.Agent
UNION ALL SELECT 'departments', COUNT(*) FROM gov.Department
UNION ALL SELECT 'teams',       COUNT(*) FROM gov.Team
UNION ALL SELECT 'skills',      COUNT(*) FROM gov.Skill
UNION ALL SELECT 'tool grants', COUNT(*) FROM gov.AgentTool
UNION ALL SELECT 'promotions',  COUNT(*) FROM gov.Promotion
UNION ALL SELECT 'vetoes',      COUNT(*) FROM gov.Officer WHERE Power = 'VETO'
UNION ALL SELECT 'named officers', COUNT(*) FROM gov.Officer WHERE Person <> N''
UNION ALL SELECT 'named agents',   COUNT(*) FROM gov.Agent   WHERE Person <> N''
UNION ALL SELECT 'NAME COLLISIONS (must be 0)',  COUNT(*) FROM gov.vw_NameCollisions
UNION ALL SELECT 'DANGEROUS GRANTS (must be 0)', COUNT(*) FROM gov.vw_DangerousGrants;
GO
""")
    return "\n".join(out)


def main() -> int:
    company = Company.load()
    OUT.write_text(build(company), encoding="utf-8")
    print(f"wrote {OUT.name} ({OUT.stat().st_size // 1024} KB)")
    print(f"  run: sqlcmd -S localhost -E -C -b -i \"{OUT}\"")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
