#!/usr/bin/env python3
"""
ru_aibotworks_archify.py — rebuild the architecture diagram from the registry.

`_builddocs/ruai-architecture.html` was generated by archify 2.17.0-dev.1 and is
excellent: Semantic Radar, Route Probe, Semantic Lens, Story Trail, guided views,
presentation stage, and a real export pipeline. Its *content* is stale — 215 agents,
13 officers, no corporate line.

We do not own archify, so we keep its viewer shell and replace only the parts that
carry meaning:

    <title>                          the document title
    archify-guided-views-data        the guided story chapters
    <h1>                             the headline
    <svg>…</svg>                     nodes, relationships, boundaries, legend
    .cards                           the three summary cards

Everything else — the fonts, the CSS, the entire interaction layer — is passed
through byte for byte. The companion `.architecture.json` is emitted too, so the
diagram can be recompiled by archify later without re-deriving anything by hand.

    python ru_aibotworks_archify.py
"""
from __future__ import annotations

import json
import re
import sys
from datetime import date
from html import escape
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ru_aibotworks_registry import Company  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SHELL = ROOT.parent / "_builddocs" / "ruai-architecture.html"
OUT_DIR = ROOT / "PORTAL"
OUT_HTML = OUT_DIR / "RU-AIBOTWORKS-diagram.html"
OUT_JSON = OUT_DIR / "RU-AIBOTWORKS-diagram.architecture.json"

CANVAS_W, CANVAS_H = 1380, 950
NS = "http://www.w3.org/2000/svg"

# Semantic sigils, copied verbatim from the archify shell so the vocabulary the
# viewer already teaches stays identical.
SIGILS = {
    "frontend": '<rect x="2" y="3" width="12" height="10" rx="2"/><path d="M2 6.5h12"/>'
                '<circle cx="4.1" cy="4.8" r=".7" class="sigil-fill"/>'
                '<circle cx="6.3" cy="4.8" r=".7" class="sigil-fill"/>',
    "backend": '<path d="M6 3 3 8l3 5M10 3l3 5-3 5"/>',
    "database": '<ellipse cx="8" cy="4" rx="5" ry="2"/>'
                '<path d="M3 4v8c0 1.1 2.2 2 5 2s5-.9 5-2V4M3 8c0 1.1 2.2 2 5 2s5-.9 5-2"/>',
    "cloud": '<path d="M4.3 12.5h7.3a2.4 2.4 0 0 0 .2-4.8 4 4 0 0 0-7.5-1.3A3.1 3.1 0 0 0 4.3 12.5Z"/>',
    "security": '<path d="M8 2.2 13 4v3.5c0 3.1-1.8 5.4-5 6.5-3.2-1.1-5-3.4-5-6.5V4Z"/>'
                '<path d="m5.8 8 1.5 1.5 3-3"/>',
    "messagebus": '<path d="M2.5 4.5h11M2.5 8h11M2.5 11.5h11"/>'
                  '<circle cx="5" cy="4.5" r="1" class="sigil-fill"/>'
                  '<circle cx="10.5" cy="8" r="1" class="sigil-fill"/>'
                  '<circle cx="7" cy="11.5" r="1" class="sigil-fill"/>',
    "external": '<rect x="2.5" y="5" width="8.5" height="8" rx="1.5"/>'
                '<path d="M8 2.5h5.5V8M13.5 2.5 7.5 8.5"/>',
}

VARIANT = {
    "default":  ("a-default",  "arrowhead",          "t-muted",      1.5),
    "emphasis": ("a-emphasis", "arrowhead-emphasis", "t-backend",    1.8),
    "security": ("a-security", "arrowhead-security", "t-security",   1.5),
    "dashed":   ("a-dashed",   "arrowhead-dashed",   "t-messagebus", 1.5),
}

LEGEND_KINDS = [
    ("frontend", "Direct"), ("backend", "Build"), ("security", "Verify & privacy"),
    ("cloud", "Workforce & corporate"), ("messagebus", "Ship & lanes"),
    ("database", "Gate & production"), ("external", "CEO"),
]


def e(x) -> str:
    return escape(str(x), quote=True)


# ─────────────────────────── geometry ───────────────────────────

def node_box(node: dict) -> tuple[float, float, float, float]:
    x, y = node["pos"]
    w, h = node["size"]
    return x, y, w, h


def elbow(points: list[tuple[float, float]], radius: float = 8) -> str:
    """Rounded orthogonal polyline, matching archify's path style."""
    if len(points) < 2:
        return ""
    if len(points) == 2:
        return f"M {points[0][0]} {points[0][1]} L {points[1][0]} {points[1][1]}"
    out = [f"M {points[0][0]} {points[0][1]}"]
    for i in range(1, len(points) - 1):
        px, py = points[i - 1]
        cx, cy = points[i]
        nx, ny = points[i + 1]
        r = min(radius, abs(cx - px) / 2 or radius, abs(cy - py) / 2 or radius,
                abs(nx - cx) / 2 or radius, abs(ny - cy) / 2 or radius)
        ix = cx - r if nx > cx or (nx == cx and px < cx) else cx + r
        iy = cy - r if ny > cy or (ny == cy and py < cy) else cy + r
        if px == cx:                       # arriving vertically
            out.append(f"L {cx} {cy - r if cy > py else cy + r}")
            out.append(f"Q {cx} {cy} {cx + r if nx > cx else cx - r} {cy}")
        else:                              # arriving horizontally
            out.append(f"L {cx - r if cx > px else cx + r} {cy}")
            out.append(f"Q {cx} {cy} {cx} {cy + r if ny > cy else cy - r}")
    out.append(f"L {points[-1][0]} {points[-1][1]}")
    return " ".join(out)


def midpoint(points: list[tuple[float, float]]) -> tuple[float, float]:
    """Midpoint of the longest straight run — where a label sits legibly."""
    best, span = points[0], -1.0
    for (x1, y1), (x2, y2) in zip(points, points[1:]):
        length = abs(x2 - x1) + abs(y2 - y1)
        if length > span:
            span, best = length, ((x1 + x2) / 2, (y1 + y2) / 2)
    return best


# ─────────────────────────── the diagram ───────────────────────────

def build_model(c: Company) -> dict:
    f = c.figures
    N = []

    def node(nid, kind, label, sublabel, pos, size, tag=None):
        entry = {"id": nid, "type": kind, "label": label, "sublabel": sublabel,
                 "pos": list(pos), "size": list(size)}
        if tag:
            entry["tag"] = tag
        N.append(entry)
        return entry

    node("ceo", "external", "CEO", f"{c.identity['ceo']['name']} · L5",
         (30, 366), (152, 64), f"{f['reserved_decisions']} reserved decisions")
    node("cto", "frontend", "cto", "L4 · triage + dispatch",
         (214, 244), (174, 58), "the only entry point")
    node("coo", "frontend", "coo", "L4 · corporate line",
         (214, 600), (174, 58), "NEW · off the /build path")
    node("data-protection-officer", "security", "data-protection-officer", "L3 · independent",
         (214, 788), (174, 58), "NEW · advises, never blocks")

    delivery = [
        ("product-owner", "frontend", "L3 · success criteria", None),
        ("design-owner", "frontend", "L3 · owns DESIGN.md", "anti-sameness"),
        ("web-architect", "backend", "L3 · picks the lane", None),
        ("data-architect", "backend", "L3 · schema + grain", None),
        ("platform-architect", "backend", "L3 · CI + Cedar", None),
        ("testing-architect", "security", "L3 · quality bar", None),
        ("quality-compliance", "security", "L3 · conformance", "VETO"),
    ]
    for i, (nid, kind, sub, tag) in enumerate(delivery):
        node(nid, kind, nid, sub, (424, 40 + i * 68), (182, 54), tag)

    corporate = [
        ("hr-director", "L3 · lifecycle + autonomy"),
        ("payroll-controller", "L3 · tokens + wall clock"),
        ("finance-controller", "L3 · budgets that halt"),
        ("service-management-lead", "L3 · SLA + change"),
    ]
    for i, (nid, sub) in enumerate(corporate):
        node(nid, "cloud", nid, sub, (424, 540 + i * 52), (182, 50), "NEW")

    node("workforce", "cloud", f"{f['workforce_total']} agents",
         f"{f['departments']} departments · {f['teams']} teams",
         (654, 204), (200, 76), "every one registered")
    node("policy", "security", "protect-mcp", "Cedar + Ed25519",
         (654, 352), (200, 62), "audit mode first")
    node("lanes", "messagebus", f"{f['lanes']} delivery lanes", "A · B · C1 · C2 · C3",
         (654, 462), (200, 62), "one per project")

    verification = [
        ("merge-authority", "security", "L2 · READ-ONLY", "blocks the merge"),
        ("security-engineer", "security", "L2 · vulnerabilities", "VETO"),
        ("sre", "security", "L2 · prod stability", "VETO"),
        ("release-manager", "messagebus", "L2 · routes failures", None),
        ("dependency-steward", "messagebus", "L2 · pins + teardown", None),
    ]
    for i, (nid, kind, sub, tag) in enumerate(verification):
        node(nid, kind, nid, sub, (902, 104 + i * 76), (180, 54), tag)

    node("prod", "database", "main", "production", (1148, 92), (172, 64))
    node("gate", "database", "the gate", f"{f['templates']} templates · 9 job families",
         (1148, 212), (172, 66), "all green or nothing")

    by_id = {n["id"]: n for n in N}

    def left(nid):
        x, y, w, h = node_box(by_id[nid]); return (x, y + h / 2)
    def right(nid):
        x, y, w, h = node_box(by_id[nid]); return (x + w, y + h / 2)
    def top(nid):
        x, y, w, h = node_box(by_id[nid]); return (x + w / 2, y)
    def bottom(nid):
        x, y, w, h = node_box(by_id[nid]); return (x + w / 2, y + h)

    C = []

    def link(cid, a, b, points, label=None, variant="default"):
        C.append({"id": cid, "from": a, "to": b, "label": label,
                  "variant": variant, "points": points})

    # CEO's three lines
    link("ceo-cto", "ceo", "cto",
         [right("ceo"), (200, 398), (200, 273), left("cto")], "/build", "emphasis")
    link("ceo-coo", "ceo", "coo",
         [right("ceo"), (200, 398), (200, 629), left("coo")], None, "default")
    link("ceo-dpo", "ceo", "data-protection-officer",
         [right("ceo"), (200, 398), (200, 817), left("data-protection-officer")],
         "GDPR Art. 38(3)", "security")

    # cto dispatches the delivery officers through one bus
    for i, (nid, *_ ) in enumerate(delivery):
        variant = "emphasis" if nid == "web-architect" else "default"
        label = "dispatch" if nid == "web-architect" else None
        link(f"cto-{nid}", "cto", nid,
             [right("cto"), (406, 273), (406, left(nid)[1]), left(nid)], label, variant)

    # coo runs the corporate line
    for nid, _ in corporate:
        link(f"coo-{nid}", "coo", nid,
             [right("coo"), (406, 629), (406, left(nid)[1]), left(nid)], None, "default")

    # the DPO advises; quality-compliance is what actually blocks
    link("dpo-qc", "data-protection-officer", "quality-compliance",
         [right("data-protection-officer"), (638, 817), (638, 492), (606, 492)],
         "raises findings", "dashed")

    # architects dispatch the workforce; platform writes policy
    link("wa-work", "web-architect", "workforce",
         [right("web-architect"), (630, 207), (630, 230), (654, 230)], "invoke by name", "emphasis")
    link("da-work", "data-architect", "workforce",
         [right("data-architect"), (630, 275), (630, 258), (654, 258)], None, "default")
    link("wa-lanes", "web-architect", "lanes",
         [right("web-architect"), (618, 207), (618, 493), left("lanes")], None, "default")
    link("pa-policy", "platform-architect", "policy",
         [right("platform-architect"), (630, 343), (630, 383), (654, 383)], "writes Cedar", "security")
    link("policy-work", "policy", "workforce",
         [top("policy"), bottom("workforce")], "receipt per call", "security")
    link("ds-policy", "dependency-steward", "policy",
         [left("dependency-steward"), (878, 441), (878, 403), (854, 403)], "pins", "dashed")

    # verification reports out of Build
    link("ta-ma", "testing-architect", "merge-authority",
         [right("testing-architect"), (866, 411), (866, 131), left("merge-authority")],
         "reports to", "security")
    for nid in ("security-engineer", "sre", "release-manager", "dependency-steward"):
        link(f"pa-{nid}", "platform-architect", nid,
             [right("platform-architect"), (884, 343), (884, left(nid)[1]), left(nid)],
             None, "default")
    link("work-review", "workforce", "merge-authority",
         [right("workforce"), (878, 242), (878, 131), left("merge-authority")],
         "candidate", "emphasis")

    # the gate
    link("review-gate", "merge-authority", "gate",
         [right("merge-authority"), (1116, 131), (1116, 245), left("gate")], "approved", "emphasis")
    for nid in ("quality-compliance", "security-engineer", "sre"):
        source = right(nid) if nid != "quality-compliance" else right("quality-compliance")
        link(f"{nid}-gate", nid, "gate",
             [source, (1130, source[1]), (1130, 252), (1148, 252)], None, "security")
    link("gate-prod", "gate", "prod",
         [top("gate"), bottom("prod")], "job success", "emphasis")
    link("gate-rm", "gate", "release-manager",
         [bottom("gate"), (1234, 320), (1100, 320), (1100, 365), (1082, 365)], "routing", "dashed")

    boundaries = [
        {"kind": "region",
         "label": f"Owned and generated — {f['officers']} officers · {f['agents_total']} agents",
         "rect": [190, 20, 1162, 856]},
        {"kind": "security-group", "label": "Verification — reports OUT of Build",
         "rect": [890, 74, 208, 250]},
        {"kind": "region", "label": "Corporate — outside the /build path",
         "rect": [200, 512, 420, 246]},
    ]

    views = [
        {"id": "decision-path", "label": "How a build reaches production",
         "focus": ["ceo", "cto", "web-architect", "workforce", "merge-authority", "gate", "prod"],
         "note": "Officers decide. The workforce builds. Verification reports outside the team it verifies."},
        {"id": "stop-buttons", "label": "The three vetoes",
         "focus": ["quality-compliance", "security-engineer", "sre", "gate"],
         "note": f"Exactly {f['vetoes']} officers can stop a release. Only the CEO overrides — and neither cto nor coo can."},
        {"id": "corporate-line", "label": "The corporate line",
         "focus": ["ceo", "coo", "hr-director", "payroll-controller", "finance-controller",
                   "service-management-lead"],
         "note": f"{f['officers_added']} officers added. Payroll meters what delivery spends, so delivery does not control its own cost."},
        {"id": "independent-privacy", "label": "Independent data protection",
         "focus": ["ceo", "data-protection-officer", "quality-compliance", "gate"],
         "note": "The DPO reports to the CEO directly and holds no veto. It raises findings; quality-compliance blocks on them."},
        {"id": "policy-plane", "label": "Policy and receipts",
         "focus": ["platform-architect", "policy", "workforce", "dependency-steward"],
         "note": "Cedar checks every tool call and emits an Ed25519 receipt into a hash chain that verifies offline."},
    ]

    cards = [
        {"dot": "cyan", "title": "Built here, not inherited",
         "items": [
             f"{f['agents_total']} agents generated from one registry — charter, registration record, tool contract, skills",
             "Every blast radius is a number and a bound, not a paragraph",
             "Editing a generated file is a defect the gate catches",
         ]},
        {"dot": "amber", "title": "Verification sits outside Build",
         "items": [
             "merge-authority reports to testing-architect, never to the architects it reviews",
             "It holds no Write and no Edit, anywhere",
             f"{f['read_only_officers']} officers are read-only by construction",
         ]},
        {"dot": "rose", "title": f"Still exactly {f['vetoes']} stop buttons",
         "items": [
             "quality-compliance, security-engineer, sre",
             f"{f['officers_added']} officers were added and the veto count did not move",
             "The DPO advises. Only the CEO overrides a veto",
         ]},
    ]

    return {
        "schema_version": 1,
        "diagram_type": "architecture",
        "meta": {
            "title": f"RU-AIBOTWORKS — {f['agents_total']} agents, {f['officers']} officers, {f['vetoes']} vetoes",
            "output": OUT_HTML.name,
            "quality_profile": "showcase",
            "visual_preset": "blueprint",
            "generated": date.today().isoformat(),
            "views": views,
        },
        "components": N,
        "boundaries": boundaries,
        "connections": C,
        "cards": cards,
    }


# ─────────────────────────── SVG rendering ───────────────────────────

def render_node(n: dict) -> str:
    x, y, w, h = node_box(n)
    kind = n["type"]
    cx = x + w / 2
    label, sub, tag = n["label"], n.get("sublabel"), n.get("tag")
    aria = f"Focus {label}" + (f", {sub}" if sub else "")
    title = " · ".join([p for p in (label, sub, tag) if p])
    rows = [f'<text data-node-label="" data-detail-anchor="" x="{cx}" y="{y + 25}" '
            f'class="t-primary" font-size="11" font-weight="600" text-anchor="middle">{e(label)}</text>']
    if sub:
        rows.append(f'<text data-detail="context" x="{cx}" y="{y + 40}" class="t-muted" '
                    f'font-size="9" text-anchor="middle">{e(sub)}</text>')
    if tag:
        rows.append(f'<text data-detail="fine" x="{cx}" y="{y + (52 if h > 58 else 50)}" '
                    f'class="t-{kind}" font-size="7" text-anchor="middle">{e(tag)}</text>')
    return (
        f'\n        <g id="node-{e(n["id"])}" data-node-id="{e(n["id"])}" '
        f'data-node-label="{e(label)}" tabindex="0" role="button" aria-label="{e(aria)}" '
        f'aria-pressed="false" data-node-kind="{kind}"'
        + (f' data-node-sublabel="{e(sub)}"' if sub else "")
        + (f' data-node-tag="{e(tag)}"' if tag else "")
        + '>\n'
        f'          <title>{e(title)}</title>\n'
        f'          <rect x="{x}" y="{y}" width="{w}" height="{h}" rx="6" class="c-mask"/>\n'
        f'          <rect x="{x}" y="{y}" width="{w}" height="{h}" rx="6" class="c-{kind}" stroke-width="1.5"/>\n'
        f'          <g aria-hidden="true" data-semantic-sigil="{kind}" class="semantic-sigil s-{kind}" '
        f'transform="translate({x + 6} {y + 6}) scale(0.6875)">{SIGILS[kind]}</g>\n'
        f'          ' + "\n          ".join(rows) + '\n        </g>'
    )


def render_edge(con: dict, key: int) -> str:
    cls, marker, _, width = VARIANT[con["variant"]]
    pts = con["points"]
    points_attr = ";".join(f"{px},{py}" for px, py in pts)
    return (
        f'\n        <path data-edge-from="{e(con["from"])}" data-edge-to="{e(con["to"])}"'
        + (f' data-edge-label="{e(con["label"])}"' if con.get("label") else "")
        + f' data-edge-key="{key}" data-edge-id="{e(con["id"])}" '
        f'data-composition-points="{points_attr}" d="{elbow(pts)}" class="{cls}" '
        f'stroke-width="{width}" marker-end="url(#{marker})"/>'
    )


def render_edge_label(con: dict, key: int) -> str:
    if not con.get("label"):
        return ""
    _, _, text_cls, _ = VARIANT[con["variant"]]
    mx, my = midpoint(con["points"])
    text = con["label"]
    width = len(text) * 4.8 + 10
    return (
        f'\n        <g data-detail="context" data-edge-from="{e(con["from"])}" '
        f'data-edge-to="{e(con["to"])}" data-edge-label="{e(text)}" data-edge-key="{key}" '
        f'data-edge-id="{e(con["id"])}">\n'
        f'          <rect x="{mx - width / 2:.1f}" y="{my - 7:.1f}" width="{width:.1f}" '
        f'height="14" rx="3" class="c-mask"/>\n'
        f'          <text x="{mx:.1f}" y="{my + 3:.1f}" class="{text_cls}" font-size="8" '
        f'text-anchor="middle">{e(text)}</text>\n        </g>'
    )


def render_boundary(b: dict, index: int) -> str:
    x, y, w, h = b["rect"]
    cls = "c-region" if b["kind"] == "region" else "c-security-group"
    return (
        f'\n        <rect data-graph-role="structural-frame" '
        f'data-composition-frame-kind="{b["kind"]}" data-composition-frame-id="{index}" '
        f'data-composition-frame-label="{e(b["label"])}" x="{x}" y="{y}" width="{w}" '
        f'height="{h}" rx="12" class="{cls}" stroke-width="1"/>'
    )


def render_boundary_label(b: dict, index: int) -> str:
    x, y, _, _ = b["rect"]
    cls = "t-cloud" if b["kind"] == "region" else "t-security"
    width = len(b["label"]) * 5.2 + 10
    return (
        f'\n        <g data-graph-role="structural-frame-label" data-composition-frame-id="{index}" '
        f'data-composition-frame-kind="{b["kind"]}" data-composition-frame-label="{e(b["label"])}">\n'
        f'          <rect data-graph-role="structural-frame-label-mask" x="{x + 4}" y="{y + 10}" '
        f'width="{width:.1f}" height="16" rx="3" class="c-mask"/>\n'
        f'          <text data-boundary-label="" x="{x + 8}" y="{y + 23}" class="{cls}" '
        f'font-size="9" font-weight="600">{e(b["label"])}</text>\n        </g>'
    )


def render_legend() -> str:
    out = [f'\n        <g data-legend="" data-legend-bridge="">\n'
           f'          <text x="40" y="{CANVAS_H - 46}" class="t-primary" font-size="12" '
           f'font-weight="650">Legend</text>']
    x = 40
    for kind, label in LEGEND_KINDS:
        width = 22 + len(label) * 6.6
        out.append(
            f'          <g data-legend-semantic-kind="{kind}" data-legend-kind="{kind}" '
            f'data-legend-label="{e(label)}" data-legend-x="{x}" '
            f'data-legend-baseline="{CANVAS_H - 26}" data-legend-width="{width:.0f}">\n'
            f'            <rect x="{x}" y="{CANVAS_H - 35}" width="16" height="10" rx="2.5" '
            f'class="c-{kind}" stroke-width="1"/>\n'
            f'            <text x="{x + 22}" y="{CANVAS_H - 26}" class="t-muted" font-size="10" '
            f'font-weight="500">{e(label)}</text>\n          </g>'
        )
        x += int(width) + 42
    out.append('        </g>')
    return "\n".join(out)


def render_svg(model: dict) -> str:
    title = model["meta"]["title"]
    parts = [
        f'<svg viewBox="0 0 {CANVAS_W} {CANVAS_H}" role="img" lang="en" '
        f'aria-labelledby="archify-diagram-title archify-diagram-description" '
        f'data-preset="blueprint" data-quality-profile="showcase">',
        f'        <title id="archify-diagram-title">{e(title)}</title>',
        '        <desc id="archify-diagram-description">The RU-AIBOTWORKS organisation and '
        'delivery path, generated from REGISTRY.</desc>',
        '''        <defs>
          <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-default" />
          </marker>
          <marker id="arrowhead-emphasis" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-emphasis" />
          </marker>
          <marker id="arrowhead-security" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-security" />
          </marker>
          <marker id="arrowhead-dashed" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" class="m-dashed" />
          </marker>
          <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
            <path d="M 40 0 L 0 0 0 40" class="c-grid" stroke-width="0.5"/>
          </pattern>
        </defs>

        <rect width="100%" height="100%" fill="url(#grid)" />''',
    ]
    for i, b in enumerate(model["boundaries"]):
        parts.append(render_boundary(b, i))
    for key, con in enumerate(model["connections"]):
        parts.append(render_edge(con, key))
    for n in model["components"]:
        parts.append(render_node(n))
    for key, con in enumerate(model["connections"]):
        label = render_edge_label(con, key)
        if label:
            parts.append(label)
    for i, b in enumerate(model["boundaries"]):
        parts.append(render_boundary_label(b, i))
    parts.append(render_legend())
    parts.append('\n      </svg>')
    return "\n".join(parts)


def render_cards(model: dict) -> str:
    cards = []
    for card in model["cards"]:
        items = "\n".join(
            f'          <li>&bull; {e(item)}</li>' for item in card["items"]
        )
        cards.append(
            f'      <div class="card">\n'
            f'        <div class="card-header">\n'
            f'          <div class="card-dot {card["dot"]}"></div>\n'
            f'          <h3>{e(card["title"])}</h3>\n'
            f'        </div>\n'
            f'        <ul>\n{items}\n        </ul>\n'
            f'      </div>'
        )
    return '    <div class="cards">\n' + "\n\n".join(cards) + "\n    </div>"


# ─────────────────────────── transplant ───────────────────────────

def transplant(shell: str, model: dict) -> str:
    title = model["meta"]["title"]

    shell = re.sub(r"<title>.*?</title>", f"<title>{e(title)} Diagram</title>", shell, count=1, flags=re.S)

    views_json = json.dumps(
        [{k: v for k, v in view.items()} for view in model["meta"]["views"]],
        ensure_ascii=False, separators=(",", ":"),
    )
    shell = re.sub(
        r'(<script id="archify-guided-views-data" type="application/json">).*?(</script>)',
        lambda m: m.group(1) + views_json + m.group(2),
        shell, count=1, flags=re.S,
    )

    shell = re.sub(r"<h1>.*?</h1>", f"<h1>{e(title)}</h1>", shell, count=1, flags=re.S)

    start = shell.index("<svg viewBox=")
    end = shell.index("</svg>", start) + len("</svg>")
    shell = shell[:start] + render_svg(model).lstrip() + shell[end:]

    cards_start = shell.index('    <div class="cards">')
    cards_end = shell.index("</div>", shell.index("</div>", shell.rindex(
        "</ul>", cards_start, shell.index("  </div>\n\n", cards_start)))) + len("</div>")
    cards_end = shell.index("\n    </div>", cards_start) + len("\n    </div>")
    shell = shell[:cards_start] + render_cards(model) + shell[cards_end:]

    shell = shell.replace(
        '<meta name="generator" content="archify 2.17.0-dev.1">',
        '<meta name="generator" content="archify 2.17.0-dev.1 viewer · '
        'PLATFORM/ru_aibotworks_archify.py content">',
        1,
    )
    return shell


def main() -> int:
    if not SHELL.exists():
        print(f"DEFECT  viewer shell missing: {SHELL}", file=sys.stderr)
        return 1
    company = Company.load()
    model = build_model(company)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(model, indent=2, ensure_ascii=False), encoding="utf-8")

    html = transplant(SHELL.read_text(encoding="utf-8"), model)
    OUT_HTML.write_text(html, encoding="utf-8")

    print(f"architecture diagram rebuilt - {len(model['components'])} nodes, "
          f"{len(model['connections'])} relationships, {len(model['meta']['views'])} guided views")
    print(f"  {OUT_HTML.relative_to(ROOT.parent)}  ({OUT_HTML.stat().st_size // 1024} KB)")
    print(f"  {OUT_JSON.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
