#!/usr/bin/env python3
"""
roster.py — generate the employee roster from the fork, never by hand.

The upstream catalogue documents 105 of its 202 agents. This walks the actual
tree instead, so every agent that exists is documented, assigned a reporting
line, and given a decision level — including the ~97 the docs never name.

    python scripts/roster.py --fork .claude/plugins --out docs/charter/08-employee-roster.md
    python scripts/roster.py --fork .claude/plugins --validate   # gate mode
"""
from __future__ import annotations
import argparse, json, re, sys
from collections import Counter, defaultdict
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Assignment rules. Every one of the 94 plugins maps to exactly one officer, so
# every agent lands deterministically. Unmapped plugin => build failure.
# ─────────────────────────────────────────────────────────────────────────────
import sys as _sys
from pathlib import Path as _P
_sys.path.insert(0, str(_P(__file__).resolve().parent))
from company import PLUGIN_OWNER, FUNCTION, DECLINED_PLUGINS, COMPANY   # single source of truth

FM = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)

def parse_agent(path: Path) -> dict | None:
    """Extract frontmatter. A file whose YAML will not parse is a defect, not a skip."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = FM.match(text)
    if not m:
        return {"file": str(path), "error": "no frontmatter — this agent will SILENTLY NEVER LOAD"}
    fm, out = m.group(1), {}
    for line in fm.splitlines():
        if ":" not in line or line.lstrip().startswith("#"):
            continue
        k, _, v = line.partition(":")
        out[k.strip()] = v.strip().strip('"').strip("'")
    # a colon inside an unquoted description is the defect that hid three
    # reviewers in the previous company. Flag it rather than silently accepting.
    desc = out.get("description", "")
    if desc and not desc.startswith(("'", '"')) and re.match(r"^\s*\w[\w\s-]*:", desc):
        out["warning"] = "description contains an unquoted colon — YAML may read it as a mapping"
    out["file"] = str(path)
    out.setdefault("name", path.stem)
    out.setdefault("model", "inherit")
    return out

def scan(fork: Path) -> tuple[list[dict], list[str]]:
    agents, problems = [], []
    for md in sorted(fork.rglob("*/agents/*.md")):
        parts = md.parts
        try:
            plugin = parts[parts.index("agents") - 1]
        except ValueError:
            problems.append(f"cannot determine plugin for {md}")
            continue
        a = parse_agent(md)
        if a.get("error"):
            problems.append(f"{md}: {a['error']}")
            continue
        if a.get("warning"):
            problems.append(f"{md}: {a['warning']}")
        officer = PLUGIN_OWNER.get(plugin)
        if officer is None:
            problems.append(f"UNMAPPED PLUGIN '{plugin}' — assign an officer in roster.py")
            continue
        a.update(plugin=plugin, reports_to=officer, function=FUNCTION[officer],
                 decision_level="L1", status="declined" if plugin in DECLINED_PLUGINS else "active")
        agents.append(a)
    return agents, problems

def render(agents: list[dict]) -> str:
    by_officer = defaultdict(list)
    for a in agents:
        by_officer[a["reports_to"]].append(a)
    L = ["# Employee roster — RU AI Botworks", "",
         "<!-- GENERATED by scripts/roster.py from the fork. Do not edit by hand. -->", "",
         f"**Engineers documented: {len(agents)}** · {COMPANY['officers']} officers · 1 CEO", "",
         "Every engineer below was found in the tree, not copied from upstream docs.",
         "Each carries a reporting line and a decision level, enforced on every build.", "",
         "## Headcount by officer", "",
         "| Officer | Function | Engineers |", "|---|---|---|"]
    for off in sorted(by_officer, key=lambda o: -len(by_officer[o])):
        L.append(f"| `{off}` | {FUNCTION[off]} | {len(by_officer[off])} |")
    mix = Counter(a["model"] for a in agents)
    L += ["", "## Model mix", "", "| Model | Engineers |", "|---|---|"]
    for m, n in mix.most_common():
        L.append(f"| {m} | {n} |")
    for off in sorted(by_officer):
        staff = sorted(by_officer[off], key=lambda a: a["name"])
        L += ["", f"## {FUNCTION[off]} — reports to `{off}` · {len(staff)} engineers", "",
              "| Engineer | Level | Model | Responsibility | Plugin | Status |",
              "|---|---|---|---|---|---|"]
        for a in staff:
            d = (a.get("description", "") or "")[:90].replace("|", "/")
            flag = "declined domain" if a["status"] == "declined" else "active"
            L.append(f"| `{a['name']}` | L1 | {a['model']} | {d} | `{a['plugin']}` | {flag} |")
    return "\n".join(L) + "\n"

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fork", type=Path, required=True)
    ap.add_argument("--out", type=Path)
    ap.add_argument("--validate", action="store_true")
    args = ap.parse_args()

    if not args.fork.exists():
        print(f"fork not found: {args.fork}", file=sys.stderr); return 2
    agents, problems = scan(args.fork)

    # Invariants 5, 6 and 12. A defect here fails the gate.
    if args.validate:
        for p in problems:
            print(f"DEFECT  {p}", file=sys.stderr)
        missing = [a["name"] for a in agents if not a.get("reports_to")]
        if missing:
            print(f"DEFECT  ungoverned agents: {missing}", file=sys.stderr)
        if problems or missing:
            print(f"\n{len(problems) + len(missing)} defect(s). Nothing promotes.", file=sys.stderr)
            return 1
        print(f"OK  {len(agents)} engineers, all governed, all reporting lines resolve.")
        return 0

    for p in problems:
        print(f"warning: {p}", file=sys.stderr)
    doc = render(agents)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(doc, encoding="utf-8")
        print(f"wrote {args.out} — {len(agents)} engineers")
    else:
        print(doc)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
